apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

resources:
  - ../base
  - 20-gateway-route.yaml

patches:
  - path: 30-replicas-patch.yaml
  - path: 31-pdb-patch.yaml

images:
  - name: harbor.nplan.local:80/neuroplan/frontend
    newTag: "ff1a436"

  - name: harbor.nplan.local:80/neuroplan/backend
    newTag: "1873ea3"
