apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

resources:
  - ../base
  - 20-httproute.yaml

images:
  - name: harbor.nplan.local:80/neuroplan/frontend
    newTag: "7eb9326"

  - name: harbor.nplan.local:80/neuroplan/backend
    newTag: "4dd7cc3"
