apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: application

resources:
  - ../base
  - 20-httproute.yaml

images:
  - name: 192.168.34.21:5000/neuroplan/frontend
    newTag: "870fecf"

  - name: 192.168.34.21:5000/neuroplan/backend
    newTag: "e34e134"
